config/routes.rb
RubyBB::Application.routes.draw do
  root :to => 'forums#index'

  resources :topics, :except => :show do
    member do
      put 'pin' => :pin
    end
  end
  get '/topics/:id.:format' => 'topics#feed', :format => :rss
  get '/topics/:id' => 'topics#show'

  resources :forums, :except => :show do
    collection do
      put 'position' => :position
    end
  end
  get '/forums/:id.:format' => 'forums#feed', :format => :rss
  get '/forums/:id' => 'forums#show'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  as :user do
    get 'register' => 'devise/registrations#new', :as => :new_user_registration
    post 'profile' => 'registrations#create', :as => :user_registration
    delete 'profile' => 'devise/registrations#destroy', :as => :user_registration
    get 'profile' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'profile' => 'registrations#update', :as => :user_registration
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  devise_for :users, :skip => [:sessions, :registrations]

  resources :users, :only => [:index, :show] do
    collection do
      get 'tokens'
      get 'ajax'
    end
    member do
      put 'bot' => :bot
    end
  end

  resources :messages

  resources :small_messages, :only => [:create, :destroy]

  resources :follows, :only => [:index, :create, :destroy]

  resources :notifications, :only => [:index, :destroy] do
    member do
      put '' => :mark_as_read
    end
    collection do
      put '' => :mark_all_as_read
      delete '' => :clear
    end
  end
  resources :bookmarks, :only => :index do
    collection do
      put '' => :mark_all_as_read
      delete '' => :clear
    end
  end

  resources :groups

  get 'check' => 'domains#check'
  get 'admin.:format' => 'domains#css', format: :css, as: :domains
  get 'admin' => 'domains#show', as: :domains
  put 'admin' => 'domains#update'
  delete 'admin/banner' => 'domains#delete_banner', as: :domain_banner

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#server_error'
  get '/500', :to => 'errors#server_error'

  get '/:id' => 'high_voltage/pages#show', :as => :static

end

app/models/message.rb
class Message < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks
  include Spammable
  include Renderable

  has_paper_trail :only => [:content]
  has_attached_file :attachment
  validates_attachment_size :attachment, :less_than => 1.megabyte

  PER_PAGE = 20
  paginates_per PER_PAGE

  acts_as_tenant(:domain)
  belongs_to :domain, :counter_cache => true
  has_many :notifications, :dependent => :destroy
  has_many :small_messages, :dependent => :destroy
  belongs_to :updater, :class_name => 'User', :foreign_key => 'updater_id'
  belongs_to :user, :counter_cache => true
  belongs_to :topic, :counter_cache => true, :touch => true
  belongs_to :forum, :counter_cache => true, :touch => true
  validates :content, :presence => true, :length => { :maximum => 32768 }
  attr_accessible :content, :attachment, :topic_id

  scope :and_stuff, lambda { select('messages.*').includes(:user, :updater, :small_messages => :user) }

  scope :graph, lambda { select(['date(created_at) as date', 'count(id) as value']).group('date') }
  scope :graph_follows, lambda { select(['date(created_at) as date', 'sum(follows_count) as value']).where('follows_count > ?', 0).group('date') }

  mapping do
    indexes :id, :index => :not_analyzed
    indexes :content, :analyzer => 'snowball'
    indexes :topic, :as => 'topic.try(:name)', :analyzer => 'snowball'
    indexes :forum, :as => 'forum.try(:name)', :analyzer => 'snowball'
    indexes :domain, :as => 'domain.try(:name)', :analyzer => 'snowball'
    indexes :user, :as => 'user.try(:name)', :analyzer => 'snowball'
    indexes :at, :as => 'created_at', :type => 'date'
  end

  before_save :set_parents
  after_create :autofollow
  after_create :update_parents, if: :topic
  after_destroy :decrement_parent_counters, if: :topic
  after_save :fire_notifications

  private

  def autofollow
    Follow.find_or_create_by_followable_type_and_followable_id_and_user_id('Topic', topic_id, user_id)
  end

  def update_parents
    topic.first_message_id = id unless topic.first_message_id
    topic.last_message_id = id
    topic.save
    forum.update_column :last_message_id, id
    if forum.parent_id
      Forum.update_counters forum.parent_id, messages_count: 1
      forum.parent.update_column :last_message_id, id
    end
  end

  def decrement_parent_counters
    if last_message_id = topic.messages.last.try(:id)
      if id == topic.last_message_id
        topic.update_column :last_message_id, last_message_id
        if id == forum.last_message_id
          forum.update_column :last_message_id, forum.all_messages.last.try(:id)
          forum.parent.update_column :last_message_id, forum.parent.all_messages.last.try(:id) if forum.parent
        end
      end
    end
    if forum.parent
      Forum.update_counters forum.parent_id, messages_count: -1
    end
  end

  def set_parents
    self.forum = Topic.find(topic_id).forum
  end

  def fire_notifications
    @user_ids.each do |uid|
      if uid != self.user_id
        Notification.fire(uid, self)
      end
    end
    Follow.not_by(self.user_id).where(:followable_id => self.user_id, :followable_type => 'User').each do |f|
      Notification.fire(f.user_id, self)
    end
    Follow.not_by(self.user_id).where(:followable_id => self.topic_id, :followable_type => 'Topic').each do |f|
      Notification.fire(f.user_id, self)
    end
    if self.topic.messages_count == 0
      Follow.not_by(self.user_id).where(:followable_id => self.forum_id, :followable_type => 'Forum').each do |f|
        Notification.fire(f.user_id, self)
      end
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!, except: :show

  # GET /messages
  # GET /messages.json
  def index
    @meta = true
    begin
      p = params
      d = "domain:#{request.host}"

      # N+1 queries in the select. I still not find a clean way to check ACL here.
      @messages = Kaminari.paginate_array(Message.search(page: params[:page], load: { include: [:user, :topic, :updater, :small_messages => :user]}) do
        query { string "#{d} #{p[:q]}", default_operator: 'AND' }
        sort { by :at, 'desc' }
      end.select{|m| can? :read, m}).page(1)

    rescue
      flash[:error] = I18n.t('search.error')
      @messages = []
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.and_stuff.find(params[:id])
    authorize! :read, @message
    @unread = true

    respond_to do |format|
      format.html { render partial: 'show', format: :html, layout: false, locals: {message: @message} }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new topic_id: params[:topic_id]
    authorize! :create, @message

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
    authorize! :update, @message
    @history = true
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])
    @message.user_id = current_user.id
    authorize! :create, @message

    respond_to do |format|
      if @message.save
        PrivatePub.publish_to "/topics/#{@message.topic_id}", {id: @message.id}
        format.html { redirect_to topic_url(@message.topic, page: Topic.find(@message.topic_id).messages.page.num_pages, anchor: "m#{@message.id}"), notice: t('messages.created') }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])
    authorize! :update, @message
    @message.updater_id = current_user.id

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to topic_url(@message.topic, page: params[:page]), notice: t('messages.updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    authorize! :destroy, @message
    if(@message == @message.topic.messages.first)
      r = forum_url(@message.forum)
      @message.topic.destroy
    else
      r = topic_url(@message.topic, page: params[:page])
      @message.destroy
    end

    respond_to do |format|
      format.html { redirect_to r }
      format.json { head :no_content }
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
= simple_form_for(@message, :url => @message.new_record? ? messages_path(:page => params[:page]) : message_path(@message, :page => params[:page]), :defaults => {:input_html => {:class => 'input-xxlarge'}}, :html => {:class => 'form-horizontal', 'data-persist' => 'garlic'}) do |f|
  = f.error_notification

  .form-inputs
    = render 'messages/textarea', f: f
    = f.input :topic_id, :as => :hidden
    .expandable
      .controls.more
        %a= t('.more')
      .details
        = f.input :attachment, :as => :file

  .form-actions
    = f.button :submit, class: @message.new_record? || @message.user_id == current_user.id ? 'btn-primary' : 'btn-warning', value: @message.new_record? ? t('common.create') : t('common.update')
    = link_to t('common.destroy'), message_path(@message, page: params[:page]), method: :delete, class: 'btn btn-danger', data: { confirm: t('common.are_you_sure') } if !@message.new_record? && can?(:destroy, @message)
    = link_to t('common.back'), topic_path(@message.topic, page: params[:page]), :class => 'btn btn-link' unless defined?(back) and !back

app/views/messages/_list.html.haml
- if @messages.any?
  = paginate @messages

  %table.table.messages
    - @messages.each do |message|
      = render 'messages/show', message: message

  = paginate @messages
- else
  %p.no_results= t('search.no_results')

- content_for :js do
  :javascript
    var values = #{@messages.map(&:user).uniq.reject{|u|!u}.map{|u|{val:u.name}}.to_json};

app/views/messages/_show.html.haml
%tr{class: "#{@folded ? 'folded' : nil} #{(@as_notifications && !message.notification_read?) || @unread ? 'unread' : nil}"}
  %td.user
    %a{name: "m#{message.id}"}
    %p= username message.user
    %p
      = render 'shared/avatar', user: message.user, size: 100
  %td
    - if @meta
      .meta
        %p.search= link_to message.topic.name, topic_path(message.topic)
    .message{ class: cycle('odd', 'even') }
      = raw message.rendered_content
      - if message.attachment.present?
        %p
          %em= link_to t('.download', name: message.attachment.instance_read(:file_name)), message.attachment.url
      - if message.user && !message.user.human?
        - if can?(:bot, message.user)
          = form_for message.user, url: bot_user_path(message.user, topic_id: message.topic_id) do |f|
            = f.submit t('.bot', name: message.user.name), name: 'bot', class: 'btn btn-danger'
            = f.submit t('.human', name: message.user.name), name: 'human', class: 'btn btn-success'
        - elsif message.user_id == current_user.try(:id)
          %p
            %em= t('.i_am_a_bot')
        - else
          %p
            %em= t('.it_is_a_bot', name: message.user.name)
    .meta
      - if message.updater && (message.updater_id != message.user_id || message.updated_at - 5.minutes > message.created_at)
        %p.date= t('.updated_by', name: message.updater.name, date: l(message.updated_at))
      - unless @history
        .small_messages
          - message.small_messages.each do |small_message|
            = render 'small_messages/show', small_message: small_message
          - if can? :create, sm = message.small_messages.build
            = simple_form_for sm, remote: true, html: { id: "new_small_message-#{message.id}" } do |f|
              = f.input :content
              = f.input :message_id, as: :hidden
              = f.submit value: t('common.create'), class: 'hidden'
  %td.ago.hidden-portrait-phone.meta
    - if @as_notifications
      %p= link_to t('common.remove'), notification_path(message.notification_id), method: :delete, rel: :nofollow, remote: true, class: 'delete_notification'
      - if !message.notification_read?
        %p.hidden= link_to t('common.read'), notification_path(message.notification_id), method: :put, rel: :nofollow, remote: true, class: 'read_notification'
    %p{title: l(message.created_at)}= time_ago_in_words message.created_at
    - if !@as_notifications && message.user && can?(:create, @message)
      %p.quote-that.btn-link{'data-user' => message.user.name, 'data-content' => message.content}= t('.quote')
    - if @history
      %p.use-that.btn-link{'data-content' => message.content}= t('.use')
    %p.action= link_to t('common.edit'), edit_message_path(message, page: params[:page]) if can? :update, message

app/views/messages/_textarea.html.haml
#wmd-panel
  #wmd-button-bar
  = f.input :content, :required => true, :input_html => {:rows => 15, :class => 'input-xxlarge wmd-input', :id => 'wmd-input'}
%table.table.messages.preview
  %tr
    %td.user
      %p= username current_user
      %p= render 'shared/avatar', user: current_user, size: 100
    %td
      #wmd-preview.wmd-panel.wmd-preview.message.odd
    %td.ago.hidden-portrait-phone.meta
      %p{title: l(Time.now)}=time_ago_in_words Time.now

app/views/messages/edit.html.haml
- content_for :title, t('.title')
%h1= t('.title')

= render 'topics/breadcrumb', topic: @message.topic, buttons: false

= render 'form'

- if can?(:history, @message) && @message.versions.any?
  %hr
  %table.table.messages
    - if @message.versions.count > 1
      - @message.versions.includes(:item).each do |v|
        = render 'show', message: v.reify if v.reify
    = render 'show', message: @message

app/views/messages/index.html.haml
%h1= t('.title')

= render 'list'

app/views/messages/new.html.haml
- content_for :title, t('.title')
%h1= t('.title')

= render 'topics/breadcrumb', topic: @message.topic, buttons: false

= render 'form'