config/routes.rb
RubyBB::Application.routes.draw do
  root :to => 'forums#index'

  resources :topics, :except => :show do
    member do
      put 'pin' => :pin
    end
  end
  get '/topics/:id.:format' => 'topics#feed', :format => :rss
  get '/topics/:id' => 'topics#show'

  resources :forums, :except => :show do
    collection do
      put 'position' => :position
    end
  end
  get '/forums/:id.:format' => 'forums#feed', :format => :rss
  get '/forums/:id' => 'forums#show'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  as :user do
    get 'register' => 'devise/registrations#new', :as => :new_user_registration
    post 'profile' => 'registrations#create', :as => :user_registration
    delete 'profile' => 'devise/registrations#destroy', :as => :user_registration
    get 'profile' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'profile' => 'registrations#update', :as => :user_registration
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  devise_for :users, :skip => [:sessions, :registrations]

  resources :users, :only => [:index, :show] do
    collection do
      get 'tokens'
      get 'ajax'
    end
    member do
      put 'bot' => :bot
    end
  end

  resources :messages

  resources :small_messages, :only => [:create, :destroy]

  resources :follows, :only => [:index, :create, :destroy]

  resources :notifications, :only => [:index, :destroy] do
    member do
      put '' => :mark_as_read
    end
    collection do
      put '' => :mark_all_as_read
      delete '' => :clear
    end
  end
  resources :bookmarks, :only => :index do
    collection do
      put '' => :mark_all_as_read
      delete '' => :clear
    end
  end

  resources :groups

  get 'check' => 'domains#check'
  get 'admin.:format' => 'domains#css', format: :css, as: :domains
  get 'admin' => 'domains#show', as: :domains
  put 'admin' => 'domains#update'
  delete 'admin/banner' => 'domains#delete_banner', as: :domain_banner

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#server_error'
  get '/500', :to => 'errors#server_error'

  get '/:id' => 'high_voltage/pages#show', :as => :static

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  include Controllable

  acts_as_tenant(:domain)
  belongs_to :domain, :counter_cache => true
  default_scope order(:position, :parent_id, :slug)

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :scoped], :scope => :domain_id

  has_many :children, :class_name => 'Forum', :foreign_key => 'parent_id'
  belongs_to :parent, :class_name => 'Forum', :foreign_key => 'parent_id', :touch => true
  has_many :topics, :dependent => :destroy
  has_many :messages, :dependent => :destroy
  has_many :follows, :as => :followable, :dependent => :destroy
  belongs_to :last_message, :class_name => 'Message', :foreign_key => 'last_message_id'
  validates :name, :presence => true, :length => { :maximum => 64 }
  validates_uniqueness_to_tenant :name, :case_sensitive => false
  validates :content, :length => { :maximum => 32768 }

  scope :with_follows, lambda { |user| select('follows.id as follow_id').joins("LEFT JOIN follows ON followable_id = forums.id AND followable_type = 'Forum' AND follows.user_id = #{user.try(:id)}") if user }

  attr_accessible :content, :name, :parent_id

  after_save :touch_parent, :if => :parent_id_was

  def all_topics
    Topic.child_of(self)
  end

  def all_messages
    Message.where(:forum_id => children.map(&:id) << id)
  end

  private

  def touch_parent
    Forum.find(parent_id_was).touch
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :feed]
  before_filter :get_stats, :only => :index
  before_filter(only: :show) { |c| c.send :check_sorting_params, Topic }

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.includes(:children, last_message: [:user, :topic]).where(:parent_id => nil).accessible_for(current_user, 'view')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @forums }
    end
  end

  def feed
    @forum = Forum.includes(:children).find(params[:id])
    authorize! :read, @forum
    @topics = Topic.includes(:user, :first_message).child_of(@forum).accessible_for(nil, 'view').order('topics.id desc').limit(10)

    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    @forum = Forum.select('forums.*').with_follows(current_user).includes(:children).find(params[:id])
    if request.path != forum_path(@forum)
      return redirect_to @forum, :status => :moved_permanently
    end
    authorize! :read, @forum

    @topics = Topic.and_stuff.with_bookmarks(current_user).child_of(@forum).accessible_for(current_user, 'view').order('topics.pinned desc').order(params[:sort] + " " + params[:direction]).page(params[:page])
    @topics = @topics.includes(:forum) if @forum.children.any?

    @pinnable = true
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @forum }
    end
  end

  # GET /forums/new
  # GET /forums/new.json
  def new
    @forum = Forum.new
    authorize! :create, @forum

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @forum }
    end
  end

  # GET /forums/1/edit
  def edit
    @forum = Forum.find(params[:id])
    authorize! :update, @forum
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(params[:forum])
    authorize! :create, @forum
    if @forum.parent_id
      @forum.position = @forum.parent.position
      @forum.parent.touch
    end

    respond_to do |format|
      if @forum.save
        format.html { redirect_to forums_url, notice: t('forums.created') }
        format.json { render json: @forum, status: :created, location: @forum }
      else
        format.html { render action: "new" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /forums/position
  def position
    authorize! :position, Forum.new
    i = 1
    params[:forums].each do |f|
      if f.present?
        f = Forum.find(f.to_i)
        f.update_column :position, i
        f.children.update_all :position => i
        i = i + 1
      end
    end

    respond_to do |format|
      format.html { redirect_to forums_url }
      format.json { head :no_content }
    end
  end

  # PUT /forums/1
  # PUT /forums/1.json
  def update
    @forum = Forum.find(params[:id])
    authorize! :update, @forum

    respond_to do |format|
      if @forum.update_attributes(params[:forum])
        format.html { redirect_to forums_url, notice: t('forums.updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum = Forum.find(params[:id])
    authorize! :destroy, @forum
    @forum.destroy

    respond_to do |format|
      format.html { redirect_to forums_url }
      format.json { head :no_content }
    end
  end

  private

  def get_stats
    @users = User.where('updated_at >= ?', 5.minutes.ago)
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_breadcrumb.html.haml
- if buttons
  - if !current_user || can?(:create, forum.topics.build)
    = link_to t('.new_topic'), new_topic_path(forum_id: forum.id), rel: 'nofollow', class: 'btn in-breadcrumb'

  - if can? :create, Follow.new
    = render 'follows/show', id: forum.follow_id, followable_id: forum.id, followable_type: 'Forum'

%ul.breadcrumb
  %li
    = link_to @domain.title, root_path
    %span.divider /
  %li.active
    = link_to forum.name, forum_path(forum)

app/views/forums/_form.html.haml
= simple_form_for(@forum, :defaults => {:input_html => {:class => 'input-xxlarge'}}, :html => {:class => 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :required => true, :input_html => {:maxlength => 64}
    = f.association :parent, :collection => Forum.where(:parent_id => nil)
    = f.input :content, :input_html => {:rows => 5}
    = field_set_tag t('acl.title') do
      .controls.help-block= t('acl.hint')
      = f.input :acl_view, :input_html => {'data-token' => true, 'data-prepopulate' => @forum.prePopulate('view')}
      = f.input :acl_read, :input_html => {'data-token' => true, 'data-prepopulate' => @forum.prePopulate('read')}
      = f.input :acl_write, :input_html => {'data-token' => true, 'data-prepopulate' => @forum.prePopulate('write')}
      = f.input :acl_admin, :input_html => {'data-token' => true, 'data-prepopulate' => @forum.prePopulate('admin')}

  .form-actions
    = f.button :submit, class: 'btn-warning', value: @forum.new_record? ? t('common.create') : t('common.update')
    = link_to t('common.destroy'), @forum, method: :delete, class: 'btn btn-danger', data: { confirm: t('common.are_you_sure') } if !@forum.new_record? && can?(:destroy, @forum)
    = link_to t('common.back'), @forum.new_record? ? forums_path : forum_path(@forum), :class => 'btn btn-link'

app/views/forums/edit.html.haml
- content_for :title, t('.title')
%h1= t('.title')

= render 'breadcrumb', forum: @forum, buttons: false

= render 'form'

app/views/forums/index.html.haml
- if @domain.users_count == 0 && @forums.empty?
  .widget
    :markdown
      #{t('home', host: request.host, setup: new_user_registration_path)}

- else
  - if @domain.content == '{{rubybb}}'
    = render 'domains/new'
  - elsif @domain.content.present?
    .widget
      = raw @domain.rendered_content
  - elsif @domain.title_was.blank?
    .alert.alert-success
      :markdown
        #{t('help.first_steps', settings: admin_path, forum: new_forum_path)}

  %h1
    = t('common.forums')
    %small=link_to t('common.new'), new_forum_path if can? :create, Forum.new

  %table.table.table-bordered{id: can?(:position, Forum) ? 'forums' : nil}
    %tbody
      - @forums.each do |forum|
        - if can? :read, forum
          %tr{id: forum.id}
            - if can? :position, forum
              %td.position
                ☰
            - cache "forum-v2-#{forum.id}-#{forum.updated_at}-#{forum.last_message_id}" do
              %td
                = link_to forum, :class => :title do
                  %p
                    %strong= forum.name
                - if forum.children.any?
                  %p
                    =raw forum.children.map{|f| link_to f.name, forum_path(f) if can? :read, f}.reject(&:nil?).join(', ')
                - if forum.content.present?
                  %p= forum.content
              %td.infos.hidden-phone
                %p= t('common.topics_count', count: forum.topics_count)
                %p= t('common.messages_count', count: forum.messages_count)
              %td.infos.hidden-portrait-phone
                - if forum.last_message
                  %p= l forum.last_message.updated_at, format: :short
                  %p
                    = t('common.by')
                    = username forum.last_message.user
  .widget
    %h4= t('common.stats')
    %p= t('.counters', topics: @domain.topics_count, messages: @domain.messages_count)
    %p
      = "#{t('.users', count: @domain.users_count)}#{t('.online', count: @users.count)}"
      = raw @users.map{|u| username u}.join(', ')

app/views/forums/new.html.haml
- content_for :title, t('.title')
%h1= t('.title')

= render 'form'

app/views/forums/show.html.haml
-# cache "forum-#{@forum.id}-topics-page#{params[:page]}-#{current_user.try(:role, @forum.id)||'anon'}-#{@forum.updated_at}" do
- if true

  - content_for :title, raw(@forum.name)
  = auto_discovery_link_tag(:rss, :format => 'rss')

  %h1
    = t('.title', name: @forum.name)
    %small= link_to t('common.edit'), edit_forum_path(@forum) if can? :update, @forum

  = render 'breadcrumb', forum: @forum, buttons: true

  = render 'topics/list'

  = render 'breadcrumb', forum: @forum, buttons: true