config/routes.rb
RubyBB::Application.routes.draw do
  root :to => 'forums#index'

  resources :topics, :except => :show do
    member do
      put 'pin' => :pin
    end
  end
  get '/topics/:id.:format' => 'topics#feed', :format => :rss
  get '/topics/:id' => 'topics#show'

  resources :forums, :except => :show do
    collection do
      put 'position' => :position
    end
  end
  get '/forums/:id.:format' => 'forums#feed', :format => :rss
  get '/forums/:id' => 'forums#show'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  as :user do
    get 'register' => 'devise/registrations#new', :as => :new_user_registration
    post 'profile' => 'registrations#create', :as => :user_registration
    delete 'profile' => 'devise/registrations#destroy', :as => :user_registration
    get 'profile' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'profile' => 'registrations#update', :as => :user_registration
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  devise_for :users, :skip => [:sessions, :registrations]

  resources :users, :only => [:index, :show] do
    collection do
      get 'tokens'
      get 'ajax'
    end
    member do
      put 'bot' => :bot
    end
  end

  resources :messages

  resources :small_messages, :only => [:create, :destroy]

  resources :follows, :only => [:index, :create, :destroy]

  resources :notifications, :only => [:index, :destroy] do
    member do
      put '' => :mark_as_read
    end
    collection do
      put '' => :mark_all_as_read
      delete '' => :clear
    end
  end
  resources :bookmarks, :only => :index do
    collection do
      put '' => :mark_all_as_read
      delete '' => :clear
    end
  end

  resources :groups

  get 'check' => 'domains#check'
  get 'admin.:format' => 'domains#css', format: :css, as: :domains
  get 'admin' => 'domains#show', as: :domains
  put 'admin' => 'domains#update'
  delete 'admin/banner' => 'domains#delete_banner', as: :domain_banner

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#server_error'
  get '/500', :to => 'errors#server_error'

  get '/:id' => 'high_voltage/pages#show', :as => :static

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include ActionView::Helpers
  include Controllable
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :scoped], :scope => :domain_id

  paginates_per 25

  acts_as_tenant(:domain)
  belongs_to :domain, :counter_cache => true
  belongs_to :viewer, :class_name => 'User', :foreign_key => 'viewer_id'
  belongs_to :first_message, :class_name => 'Message', :foreign_key => 'first_message_id'
  belongs_to :last_message, :class_name => 'Message', :foreign_key => 'last_message_id'
  belongs_to :user, :counter_cache => true
  belongs_to :forum, :counter_cache => true, :touch => true
  has_many :messages, :include => [:user], :dependent => :destroy
  has_many :follows, :as => :followable, :dependent => :destroy
  accepts_nested_attributes_for :messages
  validates :name, :presence => true, :length => { :maximum => 64 }
  validates_uniqueness_to_tenant :name, :case_sensitive => false
  validates :forum, :presence => true
  attr_accessible :name, :forum_id, :messages_attributes

  has_many :bookmarks, :dependent => :destroy

  scope :and_stuff, lambda { select('topics.*').includes(:user, :first_message, last_message: [:user]) }

  scope :with_bookmarks, lambda { |user| select('bookmarks.message_id as bookmarked_id').joins("LEFT JOIN bookmarks ON bookmarks.topic_id = topics.id AND bookmarks.user_id = #{user.try(:id)}") if user }

  scope :bookmarked_by, lambda { |user| select('bookmarks.message_id as bookmarked_id').joins("JOIN bookmarks ON bookmarks.topic_id = topics.id AND bookmarks.message_id < topics.last_message_id AND bookmarks.user_id = #{user.try(:id)}") if user }

  scope :with_follows, lambda { |user| select('follows.id as follow_id').joins("LEFT JOIN follows ON followable_id = topics.id AND followable_type = 'Topic' AND follows.user_id = #{user.try(:id)}") if user }

  scope :followed_by, lambda { |user| select('follows.id as follow_id').joins("JOIN follows ON followable_id = topics.id AND followable_type = 'Topic' AND follows.user_id = #{user.try(:id)}") if user }

  scope :child_of, lambda { |forum| where(:forum_id => forum.children.map(&:id) << forum.id) }

  after_update :update_counters
  after_create :autofollow
  after_create :increment_parent_counters, if: :forum
  after_destroy :decrement_parent_counters, if: :forum

  def self.default_column
    'updated_at'
  end

  def self.default_direction column
    %w[follows_count messages_count views_count updated_at].include?(column) ? 'desc' : 'asc'
  end

  def preview
    truncate(first_message.content, length: 100, separator: ' ', omission: '...')
  end

  def last_page
    (messages_count.to_f / Message::PER_PAGE).ceil
  end

  def last_page? page
    last_page == (page||1).to_i
  end

  def viewed_by! user
    if user && user.id != self.viewer_id
      self.update_column :viewer_id, user.id
      self.update_column :views_count, self.views_count+1
    end
  end

  private

  def autofollow
    f = Follow.new(followable_id: id, followable_type: 'Topic')
    f.user_id = user_id
    f.save
  end

  def increment_parent_counters
    if forum.parent_id
      Forum.update_counters forum.parent_id, topics_count: 1
    end
  end

  def decrement_parent_counters
    forum.update_column :last_message_id, forum.all_messages.last.try(:id)
    if forum.parent_id
      Forum.update_counters forum.parent_id, topics_count: -1
      forum.parent.update_column :last_message_id, forum.parent.all_messages.last.try(:id)
    end
  end

  def update_counters
    if forum_id_changed?
      messages.update_all forum_id: forum_id
      was = Forum.find(forum_id_was)

      if was.last_message_id == last_message_id
        was.update_column :last_message_id, was.all_messages.last.try(:id)
      end

      if was.parent_id && was.parent.last_message_id == last_message_id
        was.parent.update_column :last_message_id, was.parent.all_messages.last.try(:id)
      end

      if forum.last_message_id < last_message_id
        forum.update_column :last_message_id, last_message_id
      end

      if forum.parent_id && forum.parent.last_message_id < last_message_id
        forum.parent.update_column :last_message_id, last_message_id
      end

      Forum.update_counters forum_id_was, topics_count: -1, messages_count: -messages_count
      Forum.update_counters forum_id, topics_count: 1, messages_count: messages_count
      Forum.update_counters was.parent_id, topics_count: -1, messages_count: -messages_count if was.parent_id
      Forum.update_counters forum.parent_id, topics_count: 1, messages_count: messages_count if forum.parent_id
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :feed]

  def feed
    @topic = Topic.includes(:user).find(params[:id])
    authorize! :read, @topic
    @messages = @topic.messages.includes(:user).order('messages.id desc').limit(10)

    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.select('topics.*').with_follows(current_user).find(params[:id])
    authorize! :read, @topic

    follow_slug_changes && return
    jump_to_newest_or_bookmark && return
    current_user.try :bookmark!, @topic

    @messages = @topic.messages.and_stuff.page params[:page]
    @message = @topic.messages.build

    @topic.viewed_by!(current_user) if @topic.last_page?(params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new forum_id: params[:forum_id]
    authorize! :create, @topic
    @topic.messages.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.includes(:forum).find(params[:id])
    authorize! :update, @topic
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])
    @topic.user_id = current_user.id
    @topic.messages.first.user_id = current_user.id
    authorize! :create, @topic

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: t('topics.created') }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1/pin
  def pin
    @topic = Topic.find(params[:id])
    authorize! :pin, @topic
    @topic.update_column :pinned, !@topic.pinned
    respond_to do |format|
      format.html { redirect_to forum_url(@topic.forum), notice: t('topics.updated') }
      format.json { head :no_content }
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    params[:topic].delete :messages_attributes
    @topic = Topic.find(params[:id])
    authorize! :update, @topic

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to topic_url(@topic), notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    authorize! :destroy, @topic
    forum = @topic.forum
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to forum_url(forum) }
      format.json { head :no_content }
    end
  end

  private

  def follow_slug_changes
    if request.path != topic_path(@topic)
      return redirect_to @topic, :status => :moved_permanently
    end
  end

  def jump_to_newest_or_bookmark
    if (current_user && params.has_key?(:newest) && m_id = current_user.bookmarks.where(topic_id: @topic.id).first.try(&:message_id)) || (m_id = params[:goto])
      nb = Message.where(topic_id: @topic.id).where('id <= ?', m_id).count
      page = (nb.to_f / Message::PER_PAGE).ceil
      return redirect_to topic_url(@topic, page: page > 1 ? page : nil, anchor: "m#{m_id}")
    end
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_breadcrumb.html.haml
- if buttons
  - if !current_user || can?(:create, topic.messages.build)
    = link_to t('.new_message'), new_message_path(topic_id: topic.id), rel: 'nofollow', class: 'btn in-breadcrumb'

  - if can?(:create, Follow.new)
    = render 'follows/show', id: topic.follow_id, followable_id: topic.id, followable_type: 'Topic'

%ul.breadcrumb
  %li
    = link_to @domain.title, root_path
    %span.divider /
  %li
    = link_to topic.forum.name, forum_path(topic.forum)
    %span.divider /
  %li.active= link_to topic.name, topic_path(topic)

app/views/topics/_form.html.haml
= simple_form_for(@topic, :defaults => {:input_html => {:class => 'input-xxlarge'}}, :html => {:class => 'form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :required => true, :input_html => {:maxlength => 64}
    - if @topic.new_record?
      - if @topic.forum.children.any?
        = f.association :forum, :collection => Forum.where(:id => @topic.forum.children.map(&:id) << @topic.forum_id), :include_blank => false
      -else
        .hidden= f.association :forum
      = f.simple_fields_for :messages do |m|
        = render 'messages/textarea', f: m
    - else
      = f.association :forum, :include_blank => false
    .expandable
      .controls.more
        %a= t('.more')
      .details
        = field_set_tag t('acl.title') do
          .controls.help-block= t('acl.hint')
          = f.input :acl_view, :input_html => {'data-token' => true, 'data-prepopulate' => @topic.prePopulate('view')}
          = f.input :acl_read, :input_html => {'data-token' => true, 'data-prepopulate' => @topic.prePopulate('read')}
          = f.input :acl_write, :input_html => {'data-token' => true, 'data-prepopulate' => @topic.prePopulate('write')}
          = f.input :acl_admin, :input_html => {'data-token' => true, 'data-prepopulate' => @topic.prePopulate('admin')}

  .form-actions
    = f.button :submit, class: @topic.new_record? || @topic.user_id == current_user.id ? 'btn-primary' : 'btn-warning', value: @topic.new_record? ? t('common.create') : t('common.update')
    = link_to t('common.destroy'), @topic, method: :delete, class: 'btn btn-danger', data: { confirm: t('common.are_you_sure') } if !@topic.new_record? && can?(:destroy, @topic)
    = link_to t('common.back'), @topic.new_record? ? forum_path(@topic.forum) : topic_path(@topic), :class => 'btn btn-link'

app/views/topics/_list.html.haml
- if @topics.any?
  = paginate @topics

  %table.table.table-bordered.topics{class: @folded ? 'table-condensed' : nil}
    %tr
      - if @pinnable
        %th.icons
      %th= sortable Topic, :name, t('.topics')
      %th.fixed.number.hidden-phone= sortable Topic, :follows_count, t('.follows')
      %th.fixed.number.hidden-phone= sortable Topic, :messages_count, t('.messages')
      %th.fixed.number.hidden-phone= sortable Topic, :views_count, t('.views')
      %th.infos.hidden-portrait-phone= sortable Topic, :updated_at, t('.activity')
    - pinned = false
    - @topics.each do |topic|
      %tr{class: "#{pinned && !topic.pinned && @pinnable ? 'separator' : nil} #{@folded ? 'folded' : nil}"}
        - if @pinnable
          - if can?(:pin, topic)
            %td.pin
              - if topic.pinned
                = link_to pin_topic_path(topic), method: 'put', title: t('common.unpin') do
                  %i.icon-pushpin
              - else
                = link_to pin_topic_path(topic), method: 'put', title: t('common.pin_on') do
                  %i.icon-arrow-up
          - else
            %td
              - if topic.pinned
                %i.icon-circle-arrow-right{ title: t('common.pinned') }
        %td
          - new = current_user && topic.bookmarked_id && topic.bookmarked_id < topic.last_message_id
          = link_to topic_path(topic) + (new ? "?newest" : ""), :class => :title do
            %p
              - if new
                %i.icon-bookmark{title: t('.new_messages')}
              %span{:title => topic.preview}= topic.name
          - unless @folded
            %p
              - if @forum && topic.forum_id != @forum.id
                = t('common.in')
                = link_to topic.forum.name, forum_path(topic.forum)
              = t('common.by')
              = username topic.user
              - if topic.messages_count > 20
                –
                = link_to t('.last_page'), topic_path(topic, page: topic.last_page)
        %td.number.hidden-phone
          %p= topic.follows_count
        %td.number.hidden-phone
          %p= topic.messages_count
        %td.number.hidden-phone
          %p= topic.views_count
        %td.infos.hidden-portrait-phone
          - if topic.messages.any?
            %p= l topic.last_message.updated_at, format: :short
            - unless @folded
              %p
                = t('common.by')
                = username topic.last_message.user
      - pinned = topic.pinned

  = paginate @topics
- else
  %p.no_results= t('search.no_results')

app/views/topics/edit.html.haml
- content_for :title, t('.title')
%h1= t('.title')

= render 'breadcrumb', topic: @topic, buttons: false

= render 'form'

app/views/topics/index.html.haml
%h1 Listing topics

%table
  %tr
    %th Name
    %th User
    %th Forum
    %th Messages count
    %th
    %th
    %th

  - @topics.each do |topic|
    %tr
      %td= topic.name
      %td= topic.user
      %td= topic.forum
      %td= topic.messages_count
      %td= link_to 'Show', topic
      %td= link_to 'Edit', edit_topic_path(topic)
      %td= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Topic', new_topic_path

app/views/topics/new.html.haml
- content_for :title, t('.title')
%h1= t('.title')

= render 'forums/breadcrumb', forum: @topic.forum, buttons: false

= render 'form'

app/views/topics/show.html.haml
- content_for :title, raw(@topic.name)
= auto_discovery_link_tag(:rss, :format => 'rss')

%h1
  = t('.title', name: @topic.name)
  %small= link_to t('common.edit'), edit_topic_path(@topic) if can? :update, @topic

= render 'breadcrumb', topic: @topic, buttons: true

= render 'messages/list'

= render 'breadcrumb', topic: @topic, buttons: true

= render 'messages/form', back: false if can? :create, @message

- if @topic.messages.page.num_pages == [params[:page].to_i, 1].max
  - content_for :js do
    = subscribe_to "/topics/#{@topic.id}"
    :javascript
      $(document).ready(function() {
        $notifications = $('#faye-notifications');
        PrivatePub.subscribe('/topics/#{@topic.id}', function(data) {
          $.get('/messages/' + data.id, function(data) {
            $(data).hide().insertAfter($('table.messages:first tr:last')).show('slow');
          });
        });
      });