config/routes.rb
RubyBB::Application.routes.draw do
  root :to => 'forums#index'

  resources :topics, :except => :show do
    member do
      put 'pin' => :pin
    end
  end
  get '/topics/:id.:format' => 'topics#feed', :format => :rss
  get '/topics/:id' => 'topics#show'

  resources :forums, :except => :show do
    collection do
      put 'position' => :position
    end
  end
  get '/forums/:id.:format' => 'forums#feed', :format => :rss
  get '/forums/:id' => 'forums#show'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  as :user do
    get 'register' => 'devise/registrations#new', :as => :new_user_registration
    post 'profile' => 'registrations#create', :as => :user_registration
    delete 'profile' => 'devise/registrations#destroy', :as => :user_registration
    get 'profile' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'profile' => 'registrations#update', :as => :user_registration
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  devise_for :users, :skip => [:sessions, :registrations]

  resources :users, :only => [:index, :show] do
    collection do
      get 'tokens'
      get 'ajax'
    end
    member do
      put 'bot' => :bot
    end
  end

  resources :messages

  resources :small_messages, :only => [:create, :destroy]

  resources :follows, :only => [:index, :create, :destroy]

  resources :notifications, :only => [:index, :destroy] do
    member do
      put '' => :mark_as_read
    end
    collection do
      put '' => :mark_all_as_read
      delete '' => :clear
    end
  end
  resources :bookmarks, :only => :index do
    collection do
      put '' => :mark_all_as_read
      delete '' => :clear
    end
  end

  resources :groups

  get 'check' => 'domains#check'
  get 'admin.:format' => 'domains#css', format: :css, as: :domains
  get 'admin' => 'domains#show', as: :domains
  put 'admin' => 'domains#update'
  delete 'admin/banner' => 'domains#delete_banner', as: :domain_banner

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#server_error'
  get '/500', :to => 'errors#server_error'

  get '/:id' => 'high_voltage/pages#show', :as => :static

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  include Renderable

  has_many :users, dependent: :destroy
  has_many :forums, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :small_messages, dependent: :destroy

  validates_format_of :theme, :with => /\A#[0-9a-f]{6}\z/i
  validates_format_of :url, :with => URI::regexp(%w(http https)), :allow_blank => true

  has_attached_file :banner
  attr_accessible :banner, :content, :css, :description, :keywords, :theme, :title, :url
end

app/models/group.rb
class Group < ActiveRecord::Base
  acts_as_tenant(:domain)

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :scoped], :scope => :domain_id

  paginates_per 25

  has_many :access_controls, :as => :user, :dependent => :destroy
  has_and_belongs_to_many :users
  belongs_to :user
  attr_accessor :user_ids
  attr_accessible :name, :status, :user_ids

  validates :name, :presence => true
  validates_uniqueness_to_tenant :name, :case_sensitive => false
  validates :status, :inclusion => { :in => %w[private public] }, :allow_blank => false

  scope :for_user, lambda { |user| where('status = "public" or (status = "private" and user_id = ?)', user.id) }

  before_save :convert_user_ids

  def prePopulate
    users.map do |u|
      {id: u.id, name: u.name}
    end.to_json
  end

  private

  def convert_user_ids
    self.users = User.where(id: user_ids.split(',').map(&:to_i))
    self.users_count = self.users.count
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.for_user(current_user).includes(:users).page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    redirect_to users_url(group: params[:id])
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new
    authorize! :create, @group

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
    authorize! :update, @group
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    authorize! :create, @group
    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: t("groups.created.#{@group.status}") }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    authorize! :update, @group

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to groups_url, notice: t('groups.updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    authorize! :destroy, @group
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= simple_form_for(@group, :defaults => {:input_html => {:class => 'input-xxlarge'}}, :html => {:class => 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :required => true
    = f.input :status, :required => true, :include_blank => false, :collection => %w[private public].map{|s| [t("common.status.#{s}"), s]}
    = f.input :user_ids, :input_html => {'data-users' => true, 'data-prepopulate' => @group.prePopulate}

  .form-actions
    = f.button :submit, class: @group.new_record? || @group.user_id == current_user.id ? 'btn-primary' : 'btn-warning', value: @group.new_record? ? t('common.create') : t('common.update')
    = link_to t('common.destroy'), @group, method: :delete, class: 'btn btn-danger', data: { confirm: t('common.are_you_sure') } if !@group.new_record? && can?(:destroy, @group)
    = link_to t('common.back'), groups_path, :class => 'btn btn-link'

app/views/groups/edit.html.haml
%h1= t('.title')

= render 'form'

app/views/groups/index.html.haml
- content_for :title, t('.title')

%h1
  = t('.title')
  %small=link_to t('common.new'), new_group_path if can? :create, Group.new

.widget
  :markdown
    #{t('help.groups')}

= paginate @groups

- if @groups.any?
  %table.table.table-bordered.groups
    %tr
      %th= Group.human_attribute_name(:name)
      %th.infos.number= Group.human_attribute_name(:users_count)
      %th.infos.number= Group.human_attribute_name(:status)
      %th.infos.number= t('groups.role')
      %th.infos
    - @groups.each do |group|
      %tr
        %td= link_to group.name, users_path(group: group)
        %td.number= group.users_count
        %td.number= t("groups.status.#{group.status}")
        %td.number
          - if group.user_id == current_user.id
            = t('groups.owner')
          - elsif group.users.map(&:id).include?(current_user.id)
            = t('groups.member')
        %td.number
          - if can? :manage, group
            = link_to t('.edit'), edit_group_path(group)
- else
  %p.no_results= t('.no_results')

= paginate @groups

app/views/groups/new.html.haml
%h1= t('.title')

= render 'form'

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name
%p
  %b Status:
  = @group.status

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path